version: "3.9"
services:
  cerbos:
    container_name: cerbos
    image: ghcr.io/cerbos/cerbos:${CERBOS_VERSION:-dev}
    restart: always
    command: ["server", "--config=/conf/config.yml", "--log-level=warn", "--debug-listen-addr=:6666"]
    depends_on:
      - postgres
    volumes:
      - ${WORK_DIR}/cerbos:/conf
      - ${WORK_DIR}/policies:/policies
    ports:
      - "3592:3592"
      - "3593:3593"
      - "6666:6666"

  postgres:
    container_name: postgres
    image: postgres:14.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=cerbos
      - POSTGRES_PASSWORD=cerbos
      - POSTGRES_DB=cerbos
    volumes:
      - ${WORK_DIR}/postgres/init:/docker-entrypoint-initdb.d
      - ${WORK_DIR}/postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./conf/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: always

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    volumes:
      - ./conf/grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./conf/grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./conf/grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"
    restart: always
