---
apiVersion: v2
name: cerbos
home: https://cerbos.dev
icon: https://download.cerbos.dev/helm-charts/cerbie.png
description: |-
  A Helm chart to deploy Cerbos. Cerbos is an open core, language agnostic, scalable solution that makes user permissions and authorization simple to implement and manage by writing context-aware access control policies for your application resources.
type: application
maintainers:
  - name: Cerbos authors
    email: help+helm@cerbos.dev
keywords:
  - abac
  - authorization
  - developer tools
  - policies
  - rbac
  - security
version: "0.49.0"
appVersion: "0.49.0"
kubeVersion: ">=1.23.0-0"
