# Illustrates how to connect to Cerbos Hub
# Prerequisites:
# - Sign-up to Cerbos Hub and follow the instructions to create client credentials.
# - Create a Kubernetes secret named `cerbos-hub-credentials`:
#      kubectl create secret generic cerbos-hub-credentials \
#         --from-literal=CERBOS_HUB_CLIENT_ID=<YOUR_CLIENT_ID> \
#         --from-literal=CERBOS_HUB_CLIENT_SECRET=<YOUR_CLIENT_SECRET> \
#         --from-literal=CERBOS_HUB_WORKSPACE_SECRET=<YOUR_WORKSPACE_SECRET>

cerbos:
  config:
    # Configure the bundle storage driver
    storage:
      driver: "hub"
      hub:
        remote:
          bundleLabel: "YOUR_LABEL" # Alternatively, add `CERBOS_HUB_BUNDLE=<YOUR_LABEL>` to the secret you created above.

# Create environment variables from the secret.
envFrom:
  - secretRef:
      name: cerbos-hub-credentials
