---
site:
  title: Cerbos // Documentation
  url: https://docs.cerbos.dev
  start_page: cerbos:ROOT:index.adoc
  robots: allow
  keys:
    google_analytics: 'G-8G3G3MS838'
content:
  sources:
    - url: ./../
      branches: [HEAD]
      tags: ['v*', '!v0.0.*', '!v0.1.*', '!v0.2.*', '!v0.3.*', '!v0.4.*']
      edit_url: 'https://github.com/cerbos/cerbos/tree/{refname}/{path}'
      start_path: docs
urls:
  redirect_facility: netlify
  latest_version_segment: latest
  latest_version_segment_strategy: redirect:to
  latest_prerelease_version_segment: prerelease
asciidoc:
  attributes:
    app-name: "cerbos"
    app-version: "0.9.0"
    experimental: true
    page-pagination: true
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
output:
  destinations:
    - provider: fs
      path: ./build
      clean: true
    - provider: archive
      path: ./build/cerbos_docs.zip
      clean: true
