---
site:
  title: Cerbos // Documentation
  url: https://docs.cerbos.dev
  robots: allow
content:
  sources:
    - url: /github/workspace # Default location where GitHub actions mounts the source
      branches: ['HEAD']
      tags: ['v*', '!v0.0.0-alpha0','!v0.0.0-alpha1','!v0.0.0-alpha2','!v0.0.0-alpha3']
      edit_url: 'https://github.com/cerbos/cerbos/tree/{refname}/{path}'
      start_path: docs
asciidoc:
  attributes:
    app-name: "cerbos"
    app-version: "0.0.0-alpha4"
    page-pagination: true
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
output:
  clean: true
  dir: ./build
  destinations:
    - provider: archive
      path: ./build/cerbos_docs.zip
