name: Cache dependencies

on:
  push:
    branches:
      - main
  workflow_call:

jobs:
  changes:
    name: Check for changes
    runs-on: ubuntu-latest
    timeout-minutes: 15
    outputs:
      deps: ${{ steps.filter.outputs.deps }}
    steps:
      - name: Check out code
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - name: Check for changes
        id: filter
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3
        with:
          filters: |
            deps:
              - .github/workflows/cache.yaml
              - "**/go.mod"

  cache:
    name: Cache dependencies
    needs: changes
    if: ${{ needs.changes.outputs.deps == 'true' }}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Check out code
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - name: Free disk space
        uses: ./.github/actions/free-disk-space

      - name: Install Go and cache dependencies
        id: setup
        uses: ./.github/actions/setup-go
        with:
          write_deps_cache: true
          write_build_cache: true

      - name: Install just
        uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff # v3

      - name: Warm cache
        if: ${{ steps.setup.outputs.cache_hit != 'true' }}
        run: just warm-cache
