---
name: Vulnerability Check
on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 1,3,5"
jobs:
  runVulnerabilityCheck:
    name: Run Vulnerability Check
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Free disk space
        uses: ./.github/actions/free-disk-space

      - name: Install Go and restore cached dependencies
        uses: ./.github/actions/setup-go

      - name: Check vulnerabilities
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@master
          govulncheck ./...

      - name: Notify Slack
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@373da97827332b19e753c84d1e5b7937dbe0fbfa # v2
        with:
          channel_id: C02TMGNNL4V
          status: FAILED
          color: danger
